### ISSUE TITLE
Attacking with Drain results in attacker.attack gain in health instead of damageGiven!

### ISSUE THREAD

**Issue by rody82** [CodinGame/LegendsOfCodeAndMagic#5]
https://github.com/CodinGame/LegendsOfCodeAndMagic/blob/0ad88d8585f8ec011c42fcd91d87d470da0fe117/src/main/java/com/codingame/game/engine/GameState.java#L322

**Comment by rody82** [comment]
From rules:  "Creatures with Drain heal the player of the amount of the damage they deal (when attacking only). "

Line 322 should be:
 if (attacker.keywords.hasDrain && damageGiven > 0) healthGain = damageGiven

Example scenario:
Attacker with Attack=12 and Drain
Attacking a 1/1 creature should result in 1 health gain for the player not 12 ! 

As it stands this bug is a huge advantage for drain cards.

**Comment by acatai** [comment]
So the rules are wrongly written. (SUMMON @CGjupoulton)

This advantage was calculated-in - TESL creatures, regardless of the damage they do, heal of the full attack always.

**Comment by acatai** [comment]
Fixed to 

>  Creatures with Drain increase the player's health by the amount of the creature's <strong>attack</strong> (when attacking only).

in the English statement on the background repo; french statement todo.

**Comment by CGjupoulton** [comment]
In my mind, a 12/12 creature deals 12 damage to a 1/1 creature

**Comment by CGjupoulton** [comment]
But your fix makes it less ambiguous

**Comment by CGjupoulton** [comment]
(Except now it's unclear that you can't drain Ward minions)

**Comment by 2StepsFr0mHell** [comment]
To me, the statement is correct. And the viewer shows `-12`in this case. Issue should be closed

> Creatures with Drain heal the player of the amount of the damage they deal (when attacking only).

and

> When a creature attacks another one, they both deal damage equals to their attack to the defense of the other creature.

**Comment by acatai** [comment]
OK, so I reverted.
But the 'heal' phrase may suggest that the health cap is 30.
